sudo: false
dist: precise
language: java
matrix:
  include:
    - jdk: openjdk8
      dist: trusty
    - jdk: openjdk17
      dist: trusty
    - jdk: openjdk-ea
      dist: trusty
  allow_failures:
    - jdk: openjdk-ea
cache:
  directories:
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)