name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  build:
    permissions:
      contents: read
      checks: write
      statuses: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 21]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Java
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Run Codecov
        uses: codecov/codecov-action@288befbd1044bd1756afb0bdae077549e0ddb31f
