name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  build:
    permissions:
      contents: read
      checks: write
      statuses: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17, 24]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Run Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
